apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-api.fullname" . }}-secret
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  TURSO_AUTH_TOKEN: {{ .Values.env.secret.TURSO_AUTH_TOKEN | quote }}
