{{- if and .Values.env.secret.create (not .Values.env.secret.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-api.fullname" . }}-secret
  labels:
    {{- include "python-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.env.secret.databaseUrlKey | default "TURSO_DATABASE_URL" }}: {{ .Values.env.secret.TURSO_DATABASE_URL | quote }}
  {{ .Values.env.secret.authTokenKey | default "TURSO_AUTH_TOKEN" }}: {{ .Values.env.secret.TURSO_AUTH_TOKEN | quote }}
{{- end }}
