replicaCount: 1

image:
  repository: jhndagon11/tasks
  pullPolicy: Always
  tag: dev-22812715913-1

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

env:
  config:
    PORT: "8000"
  secret:
    create: true
    existingSecretName: ""
    databaseUrlKey: TURSO_DATABASE_URL
    authTokenKey: TURSO_AUTH_TOKEN
    TURSO_DATABASE_URL: "sqlite+aiosqlite:////tmp/local.db"
    TURSO_AUTH_TOKEN: ""

nodeSelector: {}
tolerations: []
affinity: {}
